vim.g.mapleader = ","
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.clipboard:append({ "unnamedplus" })
vim.opt.hlsearch=true
vim.opt.incsearch=true
vim.opt.ignorecase=true
vim.opt.encoding="UTF-8"
vim.opt.cursorline=true
vim.opt.signcolumn="yes"
vim.opt.scrolloff=5
vim.opt.autowrite=true
vim.opt.pumheight=15
vim.opt.confirm=true
vim.opt.expandtab=true
vim.opt.fillchars={
	foldopen = "",
	foldclose = "",
	fold = " ",
	foldsep = " ",
	diff = "╱",
	eob = " ",
}
vim.opt.foldlevel=99
vim.opt.inccommand="nosplit"
vim.opt.linebreak=true
vim.opt.list=true
vim.opt.shiftround=true
vim.opt.shiftwidth=2
vim.opt.shortmess:append({ W = true, I = true, c = true, C = true })
vim.opt.showmode=false
vim.opt.sidescrolloff=8
vim.opt.smartcase=true
vim.opt.smartindent=true
vim.opt.tabstop=2
vim.opt.termguicolors=true
vim.opt.timeoutlen=300
vim.opt.undofile=true
vim.opt.undolevels=10000
vim.opt.updatetime=200
vim.opt.virtualedit="block"
vim.opt.wildmode="longest:full,full"
vim.opt.winminwidth=5
vim.opt.wrap=false
vim.opt.cmdheight=1
